gui:
  scrollHeight: 10
  expandFocusedSidePanel: true
  showNumstatInFilesView: true
  showRandomTip: false
  showCommandLog: false
  nerdFontsVersion: '3'

git:
  paging:
    externalDiffCommand: difft --display=inline --color=always

os:
  editPreset: "nvim-remote"

customCommands:
  - key: 'r'
    context: 'files'
    description: 'Rename file'
    prompts:
      - type: 'input'
        title: 'New file name:'
        key: 'FileName'
    command: "git mv {{.SelectedFile.Name | quote}} {{.Form.FileName | quote}}"
