console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'yellow'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground = 'yellow'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╭─ '
    foreground = 'darkGray'
    background = 'transparent'
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<b>{{ .Path }}</b> '
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  filler = '<darkGray>·</>'
  overflow = 'hide'

  [[blocks.segments]]
    # Git (branch, status, user info)
    template = """\
     {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}\
     <lightYellow>{{if or (gt .Behind 0) (gt .Ahead 0)}} {{end}}{{ if gt .Behind 0 }}{{.Behind}}⇣{{ end }}{{ if gt .Ahead 0 }}{{.Ahead}}⇡{{ end }}</>\
     {{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}\
     {{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}\
     {{if not .UpstreamGone}} {{.UpstreamIcon}}{{abbrev 20 .User.Email}}{{end}} <darkGray>|</>\
     """
    foreground = 'cyan'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      branch_max_length = 20
      cache_duration = 'none'
      fetch_status = true
      fetch_upstream_icon = true
      fetch_user = true

      [blocks.segments.properties.status_formats]
        Added = '<green>+%d</>'
        Deleted = '<red>-%d</>'
        Modified = '<lightBlue>~%d</>'
        Unmerged = '<lightRed>x%d</>'
        Untracked = '<lightGreen>?%d</>'

  [[blocks.segments]]
    # execution result
    template = '{{ if gt .Code 0 }} {{ end }} {{ .FormattedMs }}'
    foreground = 'magenta'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─'
    foreground = 'darkGray'
    background = 'transparent'
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '❯'
    foreground = 'yellow'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
