#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = '╭─ '
    background = 'transparent'
    foreground = 'darkGray'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = '{{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} '
    background = 'transparent'
    foreground = 'cyan'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '<b>{{ .Path }}</b>'

    [blocks.segments.properties]
      style = 'full'



[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}<lightYellow>{{if or (gt .Behind 0) (gt .Ahead 0)}} {{end}}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }} {{.UpstreamIcon}}{{.User.Name}}'
    background = 'transparent'
    foreground = 'cyan'

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_user = true
      fetch_upstream_icon = true
      status_formats.Unmerged = '<lightRed>x%d</> '
      status_formats.Deleted = '<red>-%d</> '
      status_formats.Added = '<green>+%d</> '
      status_formats.Modified = '<lightBlue>~%d</> '
      status_formats.Untracked = '<lightGreen>?%d</> '

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    background = 'transparent'
    foreground = 'magenta'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
    ]
    template = '{{ if gt .Code 0 }} {{ end }} {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 100


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = '╰─'
    background = 'transparent'
    foreground = 'darkGray'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground = 'yellow'
    template = '❯'


[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '
