[/]
control-center=['<Super>i']
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/']
email=['<Super>m']
home=['<Super>e']
www=['<Super>b']

[custom-keybindings/custom0]
binding='<Super>Return'
command='xdg-terminal-exec'
name='Launch terminal'

[custom-keybindings/custom1]
binding='<Super>s'
command='spotify-launcher'
name='Launch Spotify'

[custom-keybindings/custom2]
binding='<Super>period'
command='gnome-characters'
name='Launch Characters'

[custom-keybindings/custom3]
binding='<Super>w'
command='wasistlos'
name='Launch WhatsApp'

[custom-keybindings/custom4]
binding='<Super>t'
command='telegram-desktop'
name='Launch Telegram'

[custom-keybindings/custom5]
binding='<Super>c'
command='code'
name='Launch VS Code'
